app:
  port: 3000

db:
  type: mysql # mysql or sqlite or mongodb or firebase

# if use Mysql, please add your DBinfo here
mysql:
  host: "127.0.0.1"
  port: 3306
  username: "user"
  password: "password"
  database: "chat_db"

# if use firebase, please add your api here
firebase:
  apiKey: # your firebase api data
  authDomain: # your firebase api data
  databaseURL: # your firebase api data
  projectId: # your firebase api data
  storageBucket: # your firebase api data
  messagingSenderId: # your firebase api data
  appId: # your firebase api data
  measurementId: # your firebase api data